###########################################################################
# KPG Past Exams Files Downoload
#    Copyright (C) <2020>  <Konstas Marmatakis> <email:marmako@gmail.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
###########################################################################

"""
    Links for KPG past exams files.
"""


languages = {
'german' : [
    "https://www.minedu.gov.gr/publications/kpgdocs/2019b/2019b_deu_b_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019b/2019b_deu_b_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019b/2019b_deu_c_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019b/2019b_deu_c_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019a/2019a_deu_a_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019a/2019a_deu_a_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019a/2019a_deu_b_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019a/2019a_deu_b_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019a/2019a_deu_c_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019a/2019a_deu_c_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018b/2018b_deu_b_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018b/2018b_deu_b_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018b/2018b_deu_c_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018b/2018b_deu_c_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018a/2018a_deu_a_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018a/2018a_deu_a_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018a/2018a_deu_b_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018a/2018a_deu_b_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018a/2018a_deu_c_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018a/2018a_deu_c_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017b/2017b_deu_b_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017b/2017b_deu_b_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017b/2017b_deu_c_text.zip",
    "https://www.minedu.gov.gr/publications/kpgdocs/2017b/2017b_deu_c_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017a/2017a_deu_a_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017a/2017a_deu_a_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017a/2017a_deu_b_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017a/2017a_deu_b_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017a/2017a_deu_c_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017a/2017a_deu_c_audio.mp3",
    "http://rcel.enl.uoa.gr/files/kpg/german/2014-05/DE_A_MAI14.zip", 
    "http://rcel.enl.uoa.gr/files/kpg/german/2014-05/DE_B_MAI14.zip", 
    "http://rcel.enl.uoa.gr/files/kpg/german/2014-05/DE_C_MAI14.zip"],

'english' : [
    "https://www.minedu.gov.gr/publications/kpgdocs/2019b/2019b_eng_b_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019b/2019b_eng_b_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019b/2019b_eng_c_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019b/2019b_eng_c_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019a/2019a_eng_a_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019a/2019a_eng_a_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019a/2019a_eng_b_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019a/2019a_eng_b_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019a/2019a_eng_c_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019a/2019a_eng_c_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018b/2018b_eng_b_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018b/2018b_eng_b_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018b/2018b_eng_c_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018b/2018b_eng_c_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018a/2018a_eng_a_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018a/2018a_eng_a_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018a/2018a_eng_b_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018a/2018a_eng_b_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018a/2018a_eng_c_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018a/2018a_eng_c_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017b/2017b_eng_b_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017b/2017b_eng_b_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017b/2017b_eng_c_text.zip",
    "https://www.minedu.gov.gr/publications/kpgdocs/2017b/2017b_eng_c_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017a/2017a_eng_a_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017a/2017a_eng_a_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017a/2017a_eng_b_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017a/2017a_eng_b_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017a/2017a_eng_c_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017a/2017a_eng_c_audio.mp3"
],
'spanish': [
    "https://www.minedu.gov.gr/publications/kpgdocs/2019b/2019b_esp_b_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019b/2019b_esp_b_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019b/2019b_esp_c_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019b/2019b_esp_c_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019a/2019a_esp_a_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019a/2019a_esp_a_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019a/2019a_esp_b_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019a/2019a_esp_b_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019a/2019a_esp_c_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019a/2019a_esp_c_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018b/2018b_esp_b_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018b/2018b_esp_b_audio.mp3",
    "https://www.minedu.gov.gr/publications/kpgdocs/2018b/2018b_esp_c_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018b/2018b_esp_c_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018a/2018a_esp_a_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018a/2018a_esp_a_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018a/2018a_esp_b_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018a/2018a_esp_b_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018a/2018a_esp_c_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018a/2018a_esp_c_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017b/2017b_esp_b_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017b/2017b_esp_b_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017b/2017b_esp_c_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017b/2017b_esp_c_audio.mp3", 
    "https://rcel2.enl.uoa.gr/kpg/files/past_papers/spanish/2014-05/ES_B_MAY14.zip", 
    "https://rcel2.enl.uoa.gr/kpg/files/past_papers/spanish/2014-05/ES_C_MAY14.zip", 
    "https://rcel2.enl.uoa.gr/kpg/files/past_papers/spanish/2014-05/ES_A_MAY14.zip"], 
'italian': [
    "https://www.minedu.gov.gr/publications/kpgdocs/2019b/2019b_ita_b_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019b/2019b_ita_b_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019b/2019b_ita_c_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019b/2019b_ita_c_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019a/2019a_ita_a_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019a/2019a_ita_a_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019a/2019a_ita_b_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019a/2019a_ita_b_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019a/2019a_ita_c_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019a/2019a_ita_c_audio.mp3",
    "https://www.minedu.gov.gr/publications/kpgdocs/2018b/2018b_ita_b_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018b/2018b_ita_b_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018b/2018b_ita_c_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018b/2018b_ita_c_audio.mp3",
    "https://www.minedu.gov.gr/publications/kpgdocs/2018a/2018a_ita_a_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018a/2018a_ita_a_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018a/2018a_ita_b_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018a/2018a_ita_b_audio.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018a/2018a_ita_c_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018a/2018a_ita_c_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017b/2017b_ita_b_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017b/2017b_ita_b_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017b/2017b_ita_c_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017b/2017b_ita_c_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017a/2017a_ita_a_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017a/2017a_ita_a_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017a/2017a_ita_b_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017a/2017a_ita_b_audio.mp3",
    "https://www.minedu.gov.gr/publications/kpgdocs/2017a/2017a_ita_c_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017a/2017a_ita_c_audio.mp3" 
],
'french': [
    "https://www.minedu.gov.gr/publications/kpgdocs/2019b/2019b_fra_b_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019b/2019b_fra_b_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019b/2019b_fra_c_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019b/2019b_fra_c_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019a/2019a_fra_a_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019a/2019a_fra_a_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019a/2019a_fra_b_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019a/2019a_fra_b_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019a/2019a_fra_c_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2019a/2019a_fra_c_audio.mp3",
    "https://www.minedu.gov.gr/publications/kpgdocs/2018b/2018b_fra_b_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018b/2018b_fra_b_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018b/2018b_fra_c_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018b/2018b_fra_c_audio.mp3",
    "https://www.minedu.gov.gr/publications/kpgdocs/2018a/2018a_fra_a_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018a/2018a_fra_a_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018a/2018a_fra_b_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018a/2018a_fra_b_audio.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018a/2018a_fra_c_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2018a/2018a_fra_c_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017b/2017b_fra_b_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017b/2017b_fra_b_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017b/2017b_fra_c_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017b/2017b_fra_c_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017a/2017a_fra_a_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017a/2017a_fra_a_audio.mp3", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017a/2017a_fra_b_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017a/2017a_fra_b_audio.mp3",
    "https://www.minedu.gov.gr/publications/kpgdocs/2017a/2017a_fra_c_text.zip", 
    "https://www.minedu.gov.gr/publications/kpgdocs/2017a/2017a_fra_c_audio.mp3" 
]
}